### ISSUE TITLE
Are you hoping to publish megrim?

### ISSUE THREAD

**Issue by endrebak** [sagrudd/megrim#1]
Just wondering :)

**Comment by sagrudd** [comment]
Megrim was intended as a toolkit for my own python based analysis of nanopore sequence data and as a framework to base a collection of analysis tutorials on. The ambition is not to publish (this is no longer a career KPI). With other planned products and a selection pressure to product manage rather than develop I suspect that this project is likely to become more of just a toy ...

**Comment by endrebak** [comment]
Understood :) Thanks!
